/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT DMFX2_CSL_BIOS_.cdb */

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj KNL_swi;
extern TSK_Obj TSK_idle;
extern TSK_Obj MainTsk;
extern TSK_Obj Tsk_LcdMenu;
extern TSK_Obj Tsk_I2c_Intc_MasterTx;
extern LOG_Obj LOG_system;
extern LOG_Obj trace;
extern SEM_Obj SEM_I2c_Intc;
extern SEM_Obj SEM_Menu;
extern SEM_Obj SEM_Int0;
extern STS_Obj IDL_busyObj;
extern STS_Obj STS_LcdMenu;
extern STS_Obj STS_I2c_Intc_MasterTx;


#ifdef __cplusplus
}
#endif /* extern "C" */
