/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT VC5505_CSL_BIOS_.cdb */

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <mbx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj KNL_swi;
extern TSK_Obj TSK_idle;
extern TSK_Obj mainTsk;
extern TSK_Obj TSK_MUSBMSCTask;
extern TSK_Obj TSK_MUSBMainTask;
extern LOG_Obj LOG_system;
extern SEM_Obj SEM_MUSBMainTaskExited;
extern SEM_Obj SEM_AbortTransferDone;
extern SEM_Obj SEM_ConnectDeviceDone;
extern SEM_Obj SEM_ResetDeviceDone;
extern SEM_Obj SEM_MUSBDMARxComplete;
extern SEM_Obj SEM_MUSBDMATxComplete;
extern SEM_Obj SEM_ClearEndpointStalltDone;
extern SEM_Obj SEM_MUSBMSCTaskExited;
extern SEM_Obj SEM_DisconnectDeviceDone;
extern SEM_Obj SEM_I2cDevBusy;
extern SEM_Obj SEM_RTCAlarmOff;
extern SEM_Obj SEM_mmcsd_dmaTransferDone;
extern MBX_Obj MBX_musb;
extern MBX_Obj MBX_msc;


#ifdef __cplusplus
}
#endif /* extern "C" */
