C55XX CSL LP: USB MUSB Functions
USB MUSB Functions
USB
Functions
void USB_init ()
CSL_UsbDevHandle USB_open (CSL_UsbDevNum devNum)
CSL_Status USB_config (CSL_UsbDevHandle hUsbDev, CSL_UsbConfig *usbCfg)
CSL_UsbEpHandle USB_requestEndpt (CSL_UsbDevHandle hUsbDev, CSL_UsbEpNum epNum, CSL_Status *status)
CSL_Status USB_releaseEndpt (CSL_UsbEpHandle hEp)
CSL_Status USB_configEndpt (CSL_UsbEpHandle hEp, CSL_UsbEpConfig *epCfg)
CSL_Status USB_resetDev (CSL_UsbDevHandle hUsbDev)
CSL_UsbEventMask USB_getEvents (CSL_UsbEpHandle hEp, CSL_Status *status)
CSL_UsbEventMask USB_peekEvents (CSL_UsbEpHandle hEp, CSL_Status *status)
CSL_Status USB_getSetupPacket (CSL_UsbDevHandle hUsbDev, CSL_UsbSetupStruct *usbSetup, Bool readFromFifo)
CSL_Status USB_postTransaction (CSL_UsbEpHandle hEp, Uint16 byteCnt, void *data, CSL_UsbIoFlags flags)
CSL_UsbBoolean USB_isTransactionDone (CSL_UsbEpHandle hEp, CSL_Status *status)
CSL_UsbByteCount USB_bytesRemaining (CSL_UsbEpHandle hEp, CSL_Status *status)
CSL_Status USB_stallEndpt (CSL_UsbEpHandle hEp)
CSL_Status USB_clearEndptStall (CSL_UsbEpHandle hEp)
CSL_UsbBoolean USB_getEndptStall (CSL_UsbEpHandle hEp, CSL_Status *status)
CSL_UsbEpHandle USB_epNumToHandle (CSL_UsbDevHandle hUsbDev, Uint16 endpt)
CSL_Status USB_abortTransaction (CSL_UsbEpHandle hEp)
CSL_Status USB_abortAllTransaction (CSL_UsbDevHandle hUsbDev)
CSL_Status USB_connectDev (CSL_UsbDevHandle hUsbDev)
CSL_Status USB_disconnectDev (CSL_UsbDevHandle hUsbDev)
CSL_Status USB_setRemoteWakeup (CSL_UsbDevHandle hUsbDev, CSL_UsbBoolean rmtWkpStat)
CSL_UsbBoolean USB_getRemoteWakeupStat (CSL_UsbDevHandle hUsbDev)
CSL_Status USB_issueRemoteWakeup (CSL_UsbDevHandle hUsbDev, Bool resumeBitVal)
CSL_Status USB_setDevAddr (CSL_UsbDevHandle hUsbDev, Uint16 addr)
CSL_UsbFrameNum USB_getFrameNo (CSL_UsbDevHandle hUsbDev)
CSL_Status USB_suspendDevice (CSL_UsbDevHandle hUsbDev)
CSL_Status USB_selfwakeup (CSL_UsbDevHandle hUsbDev, Uint32 wakeupDelay)
void USB_initPLL (void)
CSL_Status USB_setParams (CSL_UsbDevHandle hUsbDev, CSL_UsbEpHandle hEpObj[], Uint16 pSofTmrCnt)
WORD USB_getMaxPower (CSL_UsbDevHandle hUsbDev)
void USB_setFullSpeedMode (CSL_UsbDevHandle hUsbDev, Uint16 ep0DataSize)
Uint16 USB_getDataCountReadFromFifo (CSL_UsbEpHandle hEp)
Uint16 USB_findFifoSize (CSL_UsbDevHandle hUsbDev, Uint16 maxPktSize, CSL_UsbXferType xferType)
CSL_Status USB_coreEventProcessEp0 (CSL_UsbDevHandle hUsbDev)
Processing all the EP0 events for enumeration call the CDC event handler for further processing.
static CSL_Status USB_swapWords (Uint16 *dataBuffer, Uint32 dataLength)
static void USB_initDma (void)
static CSL_Status USB_initQueueManager (CSL_UsbHostPktDescr *hpdtx, Uint32 *pLinkingRam)
static void USB_dmaPopQue (Uint16 queueNum)
static void USB_dmaRxStart (DWORD dwEndpoint)
static CSL_Status USB_confDmaRx (CSL_UsbHostPktDescr *hpdrx, Uint32 packetsize, Uint16 *pRxBuffer)
static CSL_Status USB_confDmaTx (DWORD dwEndpoint, CSL_UsbHostPktDescr *hpdtx, Uint32 packetsize, Uint16 *pTxBuffer, Bool swapWords)
static void USB_dmaRxStop (DWORD dwEndpoint, Uint16 *pRxBuffer, Uint32 packetsize, Bool swapWords)
static void USB_dmaTxStart (DWORD dwEndpoint)
static void USB_dmaTxStop (DWORD dwEndpoint)
static CSL_Status USB_handleTx (CSL_UsbDevHandle hUsbDev, DWORD dwEndpoint)
static CSL_Status USB_handleRx (CSL_UsbDevHandle hUsbDev, DWORD dwEndpoint)
static CSL_Status USB_processEP0Out (CSL_UsbDevHandle hUsbDev)
static CSL_Status USB_processEP0In (CSL_UsbDevHandle hUsbDev)
static void USB_handleRxIntr (CSL_UsbDevHandle hUsbDev)
static void USB_handleTxIntr (CSL_UsbDevHandle hUsbDev)
static Bool USB_checkSpeed (CSL_UsbDevHandle hUsbDev, CSL_UsbBusSpeed *pBusSpeed)
static CSL_Status USB_readEP0Buf (CSL_UsbDevHandle hUsbDev, DWORD *pBuf)
static void USB_setConfiguration (CSL_UsbDevHandle hUsbDev, Uint16 confVal)
static Bool USB_isValidDataInFifoOut (pUsbEpStatus peps)
static void USB_flushFifo (DWORD dwEndpoint, Bool fifoDirFlag)
Function Documentation
CSL_Status USB_abortAllTransaction (CSL_UsbDevHandle hUsbDev)
============================================================================
USB_abortAllTransaction
Description
This function terminates all the data transfer in progress and free up the endpoints to post new data transfer requests.
Arguments
            hUsbDev         USB device handle
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_postTransaction function should be called successfully
Post Condition
Aborts all transactions in progress
Modifies
USB registers
Example
             Uint16             dataBuf[256];
            CSL_UsbDevHandle   hUsbDev
             CSL_UsbEpHandle    hEp;
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ....
            status = USB_postTransaction(hEp, 256, dataBuf, CSL_USB_IOFLAG_NONE);
            .....
            status = USB_abortAllTransaction(hUsbDev);
============================================================================
CSL_Status USB_abortTransaction (CSL_UsbEpHandle hEp)
============================================================================
USB_abortTransaction
Description
This function terminates the data transfer in progress and free up the endpoint to post a new data transfer request.
Arguments
            hEp         Handle to an initialized endpoint object.
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_postTransaction function should be called successfully
Post Condition
Terminates data transfer in progress
Modifies
USB registers
Example
             Uint16             dataBuf[256];
            CSL_UsbDevHandle   hUsbDev
             CSL_UsbEpHandle    hEp;
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ....
            status = USB_postTransaction(hEp, 256, dataBuf, CSL_USB_IOFLAG_NONE);
            .....
            status = USB_abortTransaction(hEp);
============================================================================
Referenced by MSC_HandleStateReset().
CSL_UsbByteCount USB_bytesRemaining (CSL_UsbEpHandle hEp, CSL_Status * status)
============================================================================
USB_bytesRemaining
Description
This API returns number of bytes waiting to be transferred from the previously posted data transfer request.
Arguments
            hEp         Handle to an initialized endpoint object.
            status      Status of the function call
Return Value CSL_UsbByteCount
Number of bytes waiting to be transferred
Pre Condition
Post transaction API should be called successfully
Post Condition
1. Returns the number of bytes waiting
2. Function call status is returned in status variable
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
CSL_ESYS_INVPARAMS - Invalid parameter
Modifies
status variable
Example
             Uint16             dataBuf[256];
            CSL_UsbDevHandle   hUsbDev
             CSL_UsbEpHandle    hEp;
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ....
            status = USB_postTransaction(hEp, 256, dataBuf, CSL_USB_IOFLAG_NONE);
            ...
            ...
            byteCount = USB_bytesRemaining(hEp ,&status);
============================================================================
static Bool USB_checkSpeed (CSL_UsbDevHandle hUsbDev, CSL_UsbBusSpeed * pBusSpeed) [inline, static]
============================================================================
USB_checkSpeed
Description
This function checks the USB bus speed
Arguments
             hUsbDev       -   USB device handle
             pBusSpeed     -   USB Bus speed variable pointer
Return Value
TRUE - Bus speed is valid
FALSE - Bus speed is invalid
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Checks the USB bus speed
Modifies
Bus speed variable
Example
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
            ....
            ....
            busSpeedStat = USB_checkSpeed(hUsbDev, hUsbDev->busSpeed);
============================================================================
References CSL_USB_BS_FULL_SPEED, and CSL_USB_BS_HIGH_SPEED.
CSL_Status USB_clearEndptStall (CSL_UsbEpHandle hEp)
============================================================================
USB_clearEndptStall
Description
This function clears an end point stall
Arguments
            hEp         Handle to an initialized endpoint object.
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_initEndptObj and USB_stallEndpt should be called successfully
Post Condition
Clears an end point stall
Modifies
USB control registers
Example
             Uint16             dataBuf[256];
            CSL_UsbDevHandle   hUsbDev
             CSL_UsbEpHandle    hEp;
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ....
            status = USB_postTransaction(hEp, 256, dataBuf, CSL_USB_IOFLAG_NONE);
            ....
            ....
            status = USB_stallEndpt(hEp);
            ....
            ....
            status = USB_clearEndptStall(hEp);
============================================================================
Referenced by AC_reqClearFeature(), CDC_reqClearFeature(), HID_reqClearFeature(), and MSC_reqClearFeature().
static CSL_Status USB_confDmaRx (CSL_UsbHostPktDescr * hpdrx, Uint32 packetsize, Uint16 * pRxBuffer) [inline, static]
============================================================================
USB_confDmaRx
Description
Configures Dma for Data receive
Arguments
             hpdrx         - Dma host packet descriptor pointer
             packetsize    - Size of the packet to receive (In Bytes)
             pRxBuffer     - Receive Data Buffer pointer
Return Value CSL_Status
CSL_SOK - Reset successful
CSL_ESYS_INVPARAMS - Invalid parameters
Pre Condition
USB_initDma and USB_initQueueManager should be called successfully
Post Condition
Receives the data from an end point
Modifies
USB Dma registers
Example
            #define CSL_USB_DATA_SIZE    (256)
            Uint16    usbDataBuf[CSL_USB_DATA_SIZE];
            CSL_UsbHostPacketDescriptor    hpdrx;
            USB_initDma();
            USB_initQueueManager(&hpdrx);
            ....
            ....
            USB_confDmaRx(&hpdrx, CSL_USB_DATA_SIZE, usbDataBuf);
============================================================================
References CSL_UsbHostPktDescr::Buffer0InfoWord0, CSL_UsbHostPktDescr::Buffer0InfoWord1, CSL_ESYS_INVPARAMS, CSL_SOK, CSL_USB_16BIT_REG_MASK, HOST_PACKET_DESCR_TYPE, IRQ_globalDisable(), IRQ_globalRestore(), CSL_UsbHostPktDescr::LinkingWord, CSL_UsbHostPktDescr::OriginalBuffer0InfoWord0, CSL_UsbHostPktDescr::OriginalBuffer0InfoWord1, PACKET_TYPE_FOR_USB, CSL_UsbHostPktDescr::PacketInfoWord0, CSL_UsbHostPktDescr::PacketInfoWord1, and CSL_UsbHostPktDescr::PacketInfoWord2.
static CSL_Status USB_confDmaTx (DWORD dwEndpoint, CSL_UsbHostPktDescr * hpdtx, Uint32 packetsize, Uint16 * pTxBuffer, Bool swapWords) [inline, static]
============================================================================
USB_confDmaTx
Description
Configures Dma for Data USB data transfer. For C5505 PG1.4 and earlier versions of the DSP, word swap is required for the data buffer before transferring the data. Parameter 'swapWords' provides facility to request for the word swap for the data buffer.
Arguments
             hpdtx         - Dma host packet descriptor pointer
             packetsize    - Size of the packet to transmit (In Bytes)
             pTxBuffer     - Data Buffer pointer
            swapWords     - Flag to request for word swap
Return Value CSL_Status
CSL_SOK - Reset successful
CSL_ESYS_INVPARAMS - Invalid parameters
Pre Condition
USB_initDma and USB_initQueueManager should be called successfully
Post Condition
transmits data to an end point
Modifies
USB Dma registers
Example
            #define CSL_USB_DATA_SIZE    (256)
            Uint16    usbDataBuf[CSL_USB_DATA_SIZE];
            CSL_UsbHostPacketDescriptor    hpdtx;
            USB_initDma();
            USB_initQueueManager(&hpdrx);
            ....
            ....
            USB_confDmaTx(&hpdrx, CSL_USB_DATA_SIZE, usbDataBuf);
============================================================================
hpdtx->PacketInfoWord1 = 0;
References CSL_UsbHostPktDescr::Buffer0InfoWord0, CSL_UsbHostPktDescr::Buffer0InfoWord1, CSL_ESYS_INVPARAMS, CSL_SOK, CSL_USB_16BIT_REG_MASK, HOST_PACKET_DESCR_TYPE, IRQ_globalDisable(), IRQ_globalRestore(), CSL_UsbHostPktDescr::LinkingWord, CSL_UsbHostPktDescr::OriginalBuffer0InfoWord0, CSL_UsbHostPktDescr::OriginalBuffer0InfoWord1, PACKET_TYPE_FOR_USB, CSL_UsbHostPktDescr::PacketInfoWord0, CSL_UsbHostPktDescr::PacketInfoWord1, CSL_UsbHostPktDescr::PacketInfoWord2, and USB_swapWords().
CSL_Status USB_config (CSL_UsbDevHandle hUsbDev, CSL_UsbConfig * usbCfg)
============================================================================
USB_config
Description
This function configures the USB device
Arguments
            hUsbDev          USB device handle
            usbConfig        USB Config structure
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_init and USB_open functions should be called successfully
Post Condition
Configures the USB device
Modifies
USB context structure
Example
            CSL_UsbDevNum    devNum;
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            devNum = CSL_USB0;
            .....
            .....
            USB_init();
            hUsbDev = USB_open(devNum);
            status = USB_config(hUsbDev, &usbCfg);
============================================================================
CSL_Status USB_configEndpt (CSL_UsbEpHandle hEp, CSL_UsbEpConfig * epCfg)
============================================================================
USB_configEndpt
Description
This function configures an endpoint object.
Arguments
            hEp           Handle to an endpoint object to be initialized.
            *epCfg        Endpoint configuration structure
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_init, USB_open, USB_config and USB_requestEndpt functions should be called successfully
Post Condition
Configures an end point object
Modifies
End point object and status structures
Example
            CSL_UsbDevNum    devNum;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            devNum = CSL_USB0;
            .....
            .....
            USB_init();
            hUsbDev = USB_open(devNum);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
============================================================================
CSL_Status USB_connectDev (CSL_UsbDevHandle hUsbDev)
============================================================================
USB_connectDev
Description
This function connects the USB module to upstream port
Arguments
            hUsbDev         USB device handle
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB init function should be called successfully.
Post Condition
Connects the USB module
Modifies
USB FADDR_POWER register
Example
            CSL_UsbDevHandle   hUsbDev
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            status = USB_connectDev(CSL_USB0);
============================================================================
CSL_Status USB_coreEventProcessEp0 (CSL_UsbDevHandle hUsbDev)
Processing all the EP0 events for enumeration call the CDC event handler for further processing.
Parameters:
hUsbDev [in] USB device handle
Returns:
Error Status
CSL_Status USB_disconnectDev (CSL_UsbDevHandle hUsbDev)
============================================================================
USB_disconnectDev
Description
This function disconnects the USB module from the upstream port
Arguments
            hUsbDev         USB device handle
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_connectDev should be called successfully
Post Condition
Disconnects the USB module.
Modifies
USB FADDR_POWER register
Example
            CSL_UsbDevHandle   hUsbDev
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            status = USB_connectDev(hUsbDev);
            ....
            status = USB_disconnectDev(hUsbDev);
============================================================================
static void USB_dmaPopQue (Uint16 queueNum) [inline, static]
============================================================================
USB_dmaPopQue
Description
Function to popup the DMA queue. DMA descriptors will be removed from the queue.
Arguments
             queueNum   - Queue number
Return Value CSL_Status
CSL_SOK - Reset successful
CSL_ESYS_INVPARAMS - Invalid parameters
Pre Condition
None
Post Condition
Popup the queue
Modifies
USB Queue manager registers
Example
            USB_dmaPopQue(24);
============================================================================
static void USB_dmaRxStart (DWORD dwEndpoint) [inline, static]
============================================================================
USB_dmaRxStart
Description
Starts Dma Receive
Arguments
             dwEndpoint    - Endpoint number that is configured for Rx
Return Value None
Pre Condition
USB_confDmaRx should be called successfully
Post Condition
Starts Dma data receive
Modifies
Data buffer
Example
            #define CSL_USB_DATA_SIZE    (256)
            Uint16    usbDataBuf[CSL_USB_DATA_SIZE];
            CSL_UsbHostPacketDescriptor    hpdrx;
            USB_initDma();
            USB_initQueueManager(&hpdrx);
            ....
            ....
            USB_confDmaRx(&hpdrx, CSL_USB_DATA_SIZE, usbDataBuf);
            ....
            ....
            USB_dmaRxStart();
============================================================================
MW It clears the wrong bit
MW, need set the DISNYET (bit 12) too
Referenced by USB_handleRx().
static void USB_dmaRxStop (DWORD dwEndpoint, Uint16 * pRxBuffer, Uint32 packetsize, Bool swapWords) [inline, static]
============================================================================
USB_dmaRxStop
Description
Stops Dma data Receive operation. For C5505 PG1.4 and earlier versions of the DSP, wordswap is required for the data buffer after completing the data reception. Parameter 'swapWords' provides facility to request for the word swap for the data buffer.
Arguments
            dwEndpoint   - Endpoint number that is configured for Rx
             pRxBuffer    -   DMA Receive data buffer
            packetsize   -   Size of the data received (In Bytes)
            swapWords    -   Flag to swap the words in the Rx buffer
Return Value None
Pre Condition
USB_dmaRxStart should be called successfully
Post Condition
Starts Dma data receive
Modifies
USB Registers
Example
            #define CSL_USB_DATA_SIZE    (256)
            Uint16    usbDataBuf[CSL_USB_DATA_SIZE];
            CSL_UsbHostPacketDescriptor    hpdrx;
            USB_confDmaRx(&hpdrx, CSL_USB_DATA_SIZE, usbDataBuf);
            ....
            ....
            USB_dmaRxStart();
            ...
            ...
            USB_dmaRxStop();
============================================================================
References USB_swapWords().
static void USB_dmaTxStart (DWORD dwEndpoint) [inline, static]
============================================================================
USB_dmaTxStart
Description
Starts Dma data transmit. DMA should be configure for the data transmit operation before calling this function. Data will be transmitted by the DMA as per the configured values.
Arguments
             dwEndpoint    - Endpoint number that is configured for Tx
Return Value None
Pre Condition
USB_confDmaTx should be called successfully
Post Condition
Starts Dma data transfer
Modifies
USB FIFO registers
Example
            #define CSL_USB_DATA_SIZE    (256)
            Uint16    usbDataBuf[CSL_USB_DATA_SIZE];
            CSL_UsbHostPacketDescriptor    hpdtx;
            USB_initDma();
            USB_initQueueManager(&hpdtx);
            ....
            ....
            USB_confDmaTx(&hpdtx, CSL_USB_DATA_SIZE, usbDataBuf);
            ....
            ....
            USB_dmaTxStart();
============================================================================
Referenced by USB_handleTx().
static void USB_dmaTxStop (DWORD dwEndpoint) [inline, static]
============================================================================
USB_dmaTxStop
Description
Stops Dma data transmit.
Arguments
             dwEndpoint    - Endpoint number that is configured for Tx
Return Value None
Pre Condition
USB_dmaTxStart should be called successfully
Post Condition
Stops Dma data receive
Modifies
USB registers
Example
            #define CSL_USB_DATA_SIZE    (256)
            Uint16    usbDataBuf[CSL_USB_DATA_SIZE];
            CSL_UsbHostPacketDescriptor    hpdtx;
            USB_confDmaTx(&hpdtx, CSL_USB_DATA_SIZE, usbDataBuf);
            ....
            ....
            USB_dmaTxStart();
            ...
            ...
            USB_dmaTxStop();
============================================================================
CSL_UsbEpHandle USB_epNumToHandle (CSL_UsbDevHandle hUsbDev, Uint16 endpt)
============================================================================
USB_epNumToHandle
Description
This function returns handle to an end point
Arguments
            hUsbDev       USB device handle
            endPt         16-bit endpoint number as specified
                           in the USB specification.
                           0x00 -> Endpt 0 Out.
                           0x01 -> Endpt 1 Out.
                            0x80 -> Endpt 0 In.
                            0x81 -> Endpt 1 In.
Return Value CSL_UsbEpHandle
Handle to the endpoint object if a valid endpoint object exists, else NULL object.
Pre Condition
USB_init function should be called successfully
Post Condition
returns End point handle
Modifies
None
Example
             Uint16             dataBuf[256];
            CSL_UsbDevHandle   hUsbDev
             CSL_UsbEpHandle    hEp;
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_epNumToHandle(hUsbDev, CSL_USB_IN_TRANSFER);
============================================================================
Referenced by AC_reqClearFeature(), AC_reqGetStatus(), AC_reqSetFeature(), CDC_reqClearFeature(), CDC_reqGetStatus(), CDC_reqSetFeature(), MSC_reqClearFeature(), MSC_reqGetStatus(), and MSC_reqSetFeature().
Uint16 USB_findFifoSize (CSL_UsbDevHandle hUsbDev, Uint16 maxPktSize, CSL_UsbXferType xferType)
============================================================================
USB_findFifoSize
Description
Determine the fifo size according to the transfer type and the maximum packet size
Arguments
            hUsbDev         USB device handle
            maxPktSize      Maximum packet size
            xferType        Transfer type
Return Value FIFO size
Pre Condition
USB_init and USB_open function should be called successfully
Post Condition
Returns FIFO size
Modifies
None
Example
            CSL_UsbDevHandle hUsbDev
            Uint16           fifoSize;
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            .....
            fifoSize = USB_findFifoSize(hUsbDev, 64);
============================================================================
static void USB_flushFifo (DWORD dwEndpoint, Bool fifoDirFlag) [inline, static]
============================================================================
USB_flushFifo
Description
Function to flush the Tx and Rx FIFO of the USB
Arguments
             dwEndpoint  - End point to which FIFO flush is required
             fifoDirFlag - Flag to indicate the FIFO direction
                           1 - Tx FIFO, 0 - Rx FIFO
Return Value None
Pre Condition
None
Post Condition
Flushes Tx/Rx FIFO
Modifies
None
Example
            //Flush Tx FIFO
            USB_flushFifo (CSL_USB_EP1, 1);
            //Flush Rx FIFO
            USB_flushFifo (CSL_USB_EP2, 0);
============================================================================
References CSL_USB_EP0.
Uint16 USB_getDataCountReadFromFifo (CSL_UsbEpHandle hEp)
============================================================================
USB_getDataCountReadFromFifo
Description
This function returns the most recent data count read from the FIFO. This function is supposed to use for the OUT end point. This function always return 0 for IN end point.
Arguments
            hEp         Handle to an initialized endpoint object.
Return Value Data count read from FIFO
Pre Condition
End point object should be initialized
Post Condition
Terminates data transfer in progress
Modifies
USB registers
Example
            CSL_UsbDevHandle hUsbDev
            CSL_UsbEpHandle  hEp
            CSL_UsbEventMask usbEvents;
            CSL_Status       *status
            Uint16           fifoDataCount;
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            .....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            .....
            fifoDataCount = USB_getDataCountReadFromFifo(hEp);
============================================================================
Referenced by MSC_verifyCBW().
CSL_UsbBoolean USB_getEndptStall (CSL_UsbEpHandle hEp, CSL_Status * status)
============================================================================
USB_getEndptStall
Description
This function checks if an endpoint is stalled.
Arguments
            hEp         Handle to an initialized endpoint object.
            status      Status of the function call
Return Value CSL_UsbBoolean
CSL_USB_TRUE - If the end point is stalled.
CSL_USB_FALSE - If the end point is not stalled
Pre Condition
Init End point API should be called successfully
Post Condition
1. Returns the end point stall status
2. Function call status is returned in status variable
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
CSL_ESYS_INVPARAMS - Invalid parameter
Modifies
status variable
Example
             Uint16             dataBuf[256];
            CSL_UsbDevHandle   hUsbDev
             CSL_UsbEpHandle    hEp;
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ...
            ...
            epStall = USB_getEndptStall(hEp, &status);
============================================================================
Referenced by AC_reqGetStatus(), CDC_reqGetStatus(), HID_reqGetStatus(), and MSC_reqGetStatus().
CSL_UsbEventMask USB_getEvents (CSL_UsbEpHandle hEp, CSL_Status * status)
============================================================================
USB_getEvents
Description
This API reads and clears all the pending USB_EVENTS associated with a particular USB endpoint.
Arguments
            hEp         Handle to an initialized endpoint object.
            status      Status of the function call
Return Value CSL_UsbEventMask
ORed combination of all the pending USB_EVENTS associated with a particular endpoint.
Pre Condition
End point object should be initialized
Post Condition
1. Clears and returns the end point events
2. Function call status is returned in status variable
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
Modifies
status variable
Example
            CSL_UsbDevHandle hUsbDev
            CSL_UsbEpHandle  hEp
            CSL_UsbEventMask usbEvents;
            CSL_Status       *status
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            .....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            .....
            usbEvents = USB_getEvents(hEp, &status);
============================================================================
CSL_UsbFrameNum USB_getFrameNo (CSL_UsbDevHandle hUsbDev)
============================================================================
USB_getFrameNo
Description
This function reads current USB frame number
Arguments
            hUsbDev         USB device handle
Return Value CSL_UsbFrameNum
Current USB frame number
Pre Condition
USB init should be called successfully
Post Condition
Returns the frame number
Modifies
None
Example
            CSL_UsbDevHandle   hUsbDev
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            ....
            status = USB_getFrameNo(hUsbDev);
============================================================================
WORD USB_getMaxPower (CSL_UsbDevHandle hUsbDev)
============================================================================
USB_getMaxPower
Description
This function returns the maximum current drawn by the device. This is to inform the host about the device power requirement. This value is passed to the host through the configuration descriptor.
Arguments
             hUsbDev     USB device handle
Return Value Maximum current drawn by the device
Pre Condition
USB_init function should be called successfully
Post Condition
Returns the maximum current drawn by the device
Modifies
None
Example
            CSL_UsbDevHandle   hUsbDev
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            .....
            maxPower = USB_getMaxPower(hUsbDev);
============================================================================
CSL_UsbBoolean USB_getRemoteWakeupStat (CSL_UsbDevHandle hUsbDev)
============================================================================
USB_getRemoteWakeupStat
Description
This function returns the remote wake up feature status.
Arguments
            hUsbDev         USB device handle
Return Value CSL_UsbBoolean
CSL_USB_TRUE - Remote wakeup feature is enabled.
CSL_USB_FALSE - Remote wakeup feature is disabled.
Pre Condition
USB_setRemoteWakeup function should be called successfully
Post Condition
Returns remote wakeup status
Modifies
None
Example
            CSL_Status        status;
            CSL_UsbBoolean    rmtWkpStat
            status = USB_setRemoteWakeup(hUsbDev, CSL_USB_TRUE);
            if(status == CSL_SOK)
            {
                rmtWkpStat = USB_getRemoteWakeupStat(hUsbDev);
            }
============================================================================
Referenced by AC_reqGetStatus(), CDC_reqGetStatus(), HID_reqGetStatus(), and MSC_reqGetStatus().
CSL_Status USB_getSetupPacket (CSL_UsbDevHandle hUsbDev, CSL_UsbSetupStruct * usbSetup, Bool readFromFifo)
============================================================================
USB_getSetupPacket
Description
This function read the setup packet from the setup data buffer. This function can be used to read the setup packet from the FIFO or we can read the setup packet from the USB context structure. We can choose one of two options using readFromFifo parameter. If readFromFifo is TRUE setup packet is read from the FIFO. If readFromFifo is FALSE setup packet is read from the context structure. Setup packet should be read from FIFO when this function is called from interrupt handler(In this case read packet is stored in context structure) and setup packet should be read from USB context structure when this function is called from MSC layer.
Arguments
            hUsbDev        USB device handle
            usbSetup       Pointer to setup structure
            readFromFifo   TRUE if setup packet should be read from FIFO
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_init and USB_open should be called successfully
Post Condition
USB setup structure is populated
Modifies
None
Example
            CSL_UsbDevHandle      hUsbDev
            CSL_UsbSetupStruct    usbSetup;
            CSL_Status            status;
            CSL_UsbConfig         usbConfig
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            ....
            status = USB_getSetupPacket(hUsbDev, &usbSetup , TRUE);
============================================================================
static CSL_Status USB_handleRx (CSL_UsbDevHandle hUsbDev, DWORD dwEndpoint) [inline, static]
============================================================================
USB_handleRx
Description
Receives the data over the non-control end points This function can read the data in polled mode or using CPPI DMA. For the DMA mode operation opmode needs to be set to DMA using USB_init() API and CPPI DMA needs to be configured for USB Rx operation using USB_confDmaRx() API before calling this function.
USB DMA will be used when the data to be received is 64 or 512 bytes. CPU will be used to receive any other length of data.
Data to be recived will be read from the Rx FIFO one packet at a time. Legth of the packet will be decided based on the maximum packet size assigned to the Rx FIFO. In case of poll mode operation complete transfer callback function will be invoked after reading all the packets from the Rx FIFO. In case of DMA mode operation complete transfer callback will be invoked for each packet read. Complete transfer callback function is supposed to wait for DMA transfer completion.
Number of bytes read from FIFO in each transaction will be stored in 'pTransfer->prevTxferLen'. This value will be 64 or 512 when DMA mode is enabled and DMA is used for the data transfer. Other cases indicates that CPU mode is enabled or CPU is used for data transfer.
Arguments
             hUsbDev       -   USB device handle
             dwEndpoint    -   End point number
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Reads data from an end point
Modifies
USB Data buffer
Example
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
            ....
            ....
            status = USB_handleRx(hUsbDev, CSL_USB_EP2);
============================================================================
References CSL_UsbTransfer::cbBuffer, CSL_UsbTransfer::cbTransferred, CSL_UsbContext::completeTransferCallback, CSL_ESYS_INVPARAMS, CSL_SOK, CSL_USB_ISO, CSL_USB_MIN, CSL_UsbEpStatus::dwPacketSizeAssigned, CSL_UsbTransfer::fComplete, CSL_UsbContext::fWaitingOnFlagB, CSL_UsbContext::opMode, CSL_UsbContext::pEpStatus, CSL_UsbEpStatus::pFifoAddr, CSL_UsbTransfer::prevTxferLen, CSL_UsbEpStatus::pTransfer, CSL_UsbTransfer::pvBuffer, USB_dmaRxStart(), and CSL_UsbEpStatus::xferType.
static void USB_handleRxIntr (CSL_UsbDevHandle hUsbDev) [inline, static]
============================================================================
USB_handleRxIntr
Description
This function handles USb receive interrupts. This function is provided to be used with MSC module. For standalone MUSB operation this function is not required This function works only if EP2 configured for Rx
Arguments
             hUsbDev      -  USB device handle
Return Value None
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Handles Rx interrupt
Modifies
USb registers
Example
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
            ....
            ....
            status = USB_handleRxIntr(hUsbDev);
============================================================================
References CSL_USB_EP2, CSL_USB_ISO, CSL_UsbContext::fSetupPktCmd, CSL_UsbContext::fWaitingOnFlagB, CSL_UsbContext::pEpStatus, and CSL_UsbEpStatus::xferType.
static CSL_Status USB_handleTx (CSL_UsbDevHandle hUsbDev, DWORD dwEndpoint) [inline, static]
============================================================================
USB_handleTx
Description
Transmits the data over the non-control end points. This function can transmit the data in polled mode or using CPPI DMA. For the DMA mode operation opmode needs to be set to DMA using USB_init() API and CPPI DMA needs to be configured for USB Tx operation using USB_confDmaTx() API before calling this function.
USB DMA will be used when the data to be transferred is 64 or 512 bytes. CPU will be used to transfer any other length of data.
Data to be sent will be copied to the Tx FIFO one packet at a time. Legth of the packet will be decided based on the maximum packet size assigned to the Tx FIFO. In case of poll mode operation complete transfer callback function will be invoked after copying all the packets to the Tx FIFO. In case of DMA mode operation complete transfer callback will be invoked for each packet transferred. Complete transfer callback function is supposed to wait for DMA transfer completion.
Number of bytes written to FIFO in each transaction will be stored in 'pTransfer->prevTxferLen'. This value will be 64 or 512 when DMA mode is enabled and DMA is used for the data transfer. Other cases indicates that CPU mode is enabled or CPU is used for data transfer.
Arguments
             hUsbDev       -   USB device handle
             dwEndpoint    -   End point number
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Writes data to an end point
Modifies
USB FIFO registers
Example
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
            ....
            ....
            status = USB_handleTx(hUsbDev, CSL_USB_EP1);
============================================================================
References CSL_UsbTransfer::cbBuffer, CSL_UsbTransfer::cbTransferred, CSL_UsbContext::completeTransferCallback, CSL_ESYS_INVPARAMS, CSL_SOK, CSL_USB_IOFLAG_NOT, CSL_USB_ISO, CSL_USB_MIN, CSL_UsbEpStatus::dwPacketSizeAssigned, CSL_UsbTransfer::fComplete, CSL_UsbEpStatus::fStalled, CSL_UsbContext::fWaitingOnFlagA, CSL_UsbTransfer::ioFlags, CSL_UsbContext::opMode, CSL_UsbContext::pEpStatus, CSL_UsbEpStatus::pFifoAddr, CSL_UsbTransfer::prevTxferLen, CSL_UsbEpStatus::pTransfer, CSL_UsbTransfer::pvBuffer, USB_dmaTxStart(), and CSL_UsbEpStatus::xferType.
static void USB_handleTxIntr (CSL_UsbDevHandle hUsbDev) [inline, static]
============================================================================
USB_handleTxIntr
Description
This function handles USB transmit interrupts.
Arguments
             hUsbDev      -  USB device handle
Return Value None
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Handles Tx interrupt
Modifies
USb registers
Example
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
            ....
            ....
            status = USB_handleTxIntr(hUsbDev);
============================================================================
usbRegisters->INDEX_TESTMODE |= CSL_USB_EP1;
References CSL_USB_EP2.
void USB_init ()
============================================================================
USB_init
Description
This function initializes USB module
Arguments
            None
Return Value
None
Pre Condition
None
Post Condition
Initializes the USB module
Modifies
None
Example
            USB_init();
============================================================================
static void USB_initDma (void) [inline, static]
============================================================================
USB_initDma
Description
Initializes the Dma
Arguments
            None
Return Value None
Pre Condition
USB_init should be called successfully
Post Condition
Initializes USB Dma
Modifies
USB Dma registers
Example
            USB_init();
            ....
            ....
            USB_initDma();
============================================================================
References CSL_USB_RXGCR1_DEFVAL, CSL_USB_RXGCR2_DEFVAL, IRQ_globalDisable(), and IRQ_globalRestore().
void USB_initPLL (void)
============================================================================
USB_initPLL
Description
Initializes PLL for USB operation. This function initializes the PLL to 100 MHz. For configuring PLL to any other frequency use PLL module.
Arguments
                   None
Return Value None
Pre Condition
None
Post Condition
Initializes PLL
Modifies
PLL registers
Example
            USB_initPLL();
============================================================================
static CSL_Status USB_initQueueManager (CSL_UsbHostPktDescr * hpdtx, Uint32 * pLinkingRam) [inline, static]
============================================================================
USB_initQueueManager
Description
Initializes the Dma queue manager.
Arguments
             hpdtx         - Dma host packet transmit descriptor pointer
            pLinkingRam   - Pointer to linking RAM data buffer
Return Value CSL_Status
CSL_SOK - Reset successful
CSL_ESYS_INVPARAMS - Invalid parameters
Pre Condition
USB_initDma should be called successfully
Post Condition
Initializes queue manager
Modifies
USB Queue manager registers
Example
            CSL_UsbHostPacketDescriptor    hpdtx;
            USB_init();
            ....
            ....
            USB_initDma();
            USB_initQueueManager(&hpdrx);
============================================================================
References CSL_ESYS_INVPARAMS, CSL_SOK, CSL_USB_16BIT_REG_MASK, CSL_USB_16BIT_REG_SHIFT, CSL_USB_LRAM0SIZE_DEFVAL, CSL_USB_QMEMRCTRL2_DEFVAL, IRQ_globalDisable(), and IRQ_globalRestore().
CSL_Status USB_issueRemoteWakeup (CSL_UsbDevHandle hUsbDev, Bool resumeBitVal)
============================================================================
USB_issueRemoteWakeup
Description
This function issues a remote wakeup signal to the host. NOTE: For remote wakeup protocol application program needs to call this function two times. In the first call resumeBitVal should be TRUE and in the second call resumeBitVal should be FALSE. Application should give a delay of 2 - 15 mSecs between the two calls. This is to avoid delays internal to the CSL module
Arguments
            hUsbDev          USB device handle
            resumeBitVal     Value of the resume bit - TRUE or FALSE
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_setRemoteWakeup function should be called successfully
Post Condition
Issues a remote wake up signal.
Modifies
USB FADDR POWER register
Example
            CSL_Status    status;
            status = USB_setRemoteWakeup(hUsbDev, CSL_USB_TRUE);
            if(status == CSL_SOK)
            {
                status = USB_issueRemoteWakeup(hUsbDev, TRUE);
            }
============================================================================
CSL_UsbBoolean USB_isTransactionDone (CSL_UsbEpHandle hEp, CSL_Status * status)
============================================================================
USB_isTransactionDone
Description
This function returns the status of the previously posted data transfer request.
Arguments
            hEp         Handle to an initialized endpoint object.
            status      Status of the function call
Return Value CSL_UsbBoolean
CSL_USB_TRUE - If the previously posted transfer is completed.
CSL_USB_FALSE - If the previously posted transfer is not completed.
Pre Condition
Post transaction API should be called successfully
Post Condition
1. Returns the previous transaction status
2. Function call status is returned in status variable
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
CSL_ESYS_INVPARAMS - Invalid parameter
Modifies
status variable
Example
             Uint16             dataBuf[256];
            CSL_UsbDevHandle   hUsbDev
             CSL_UsbEpHandle    hEp;
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ....
            status = USB_postTransaction(hEp, 256, dataBuf, CSL_USB_IOFLAG_NONE);
            ...
            ...
            tscStatus = USB_isTransactionDone(hEp ,&status);
============================================================================
Referenced by MSC_HandleStateSendCSW(), MSC_HandleStateSendData(), and MSC_HandleStateSendStall().
static Bool USB_isValidDataInFifoOut (pUsbEpStatus peps) [inline, static]
============================================================================
USB_isValidDataInFifoOut
Description
This function checks validity of the data in the output FIFO
Arguments
             peps      -   End point status structure pointer
Return Value
TRUE - FIFO out has valid data
FALSE - FIFO out no has valid data
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Checks the data in FIFO Out
Modifies
None
Example
            Bool             fifoStatus;
            pUsbEpStatus     peps;
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
            ....
            ....
            fifoStatus = USB_isValidDataInFifoOut(peps);
============================================================================
References CSL_USB_EP1, CSL_USB_EP2, CSL_USB_EP3, CSL_USB_EP4, CSL_USB_ISO, CSL_UsbEpStatus::dataReadFromFifo, CSL_UsbEpStatus::dwEndpoint, and CSL_UsbEpStatus::xferType.
CSL_UsbDevHandle USB_open (CSL_UsbDevNum devNum)
============================================================================
USB_open
Description
This function returns handle to USB device
Arguments
            devNum        USB device number
Return Value CSL_UsbDevHandle
Valid handle - Returned for success
NULL - Invalid parameter
Pre Condition
USB_init function should be called successfully
Post Condition
Returns handle to USB device which will be used by other functions
Modifies
USB context structure
Example
            CSL_UsbDevNum    devNum;
            CSL_UsbDevHandle hUsbDev;
            devNum = CSL_USB0;
            .....
            .....
            USB_init();
            hUsbDev = USB_open(devNum);
============================================================================
CSL_UsbEventMask USB_peekEvents (CSL_UsbEpHandle hEp, CSL_Status * status)
============================================================================
USB_peekEvents
Description
This function read all the pending USB_EVENTS associated with a particular USB endpoint
Arguments
            hEp         Handle to an initialized endpoint object.
            status      Status of the function call
Return Value CSL_UsbEventMask
ORed combination of all the pending USB_EVENTS associated with a particular endpoint.
Pre Condition
End point object should be initialized
Post Condition
1. Returns the end point events
2. Function call status is returned in status variable
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
Modifies
status variable
Example
            CSL_UsbDevHandle hUsbDev
            CSL_UsbEpHandle  hEp
            CSL_UsbEventMask usbEvents;
            CSL_Status       *status
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            .....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            .....
            usbEvents = USB_peekEvents(hEp, &status);
============================================================================
CSL_Status USB_postTransaction (CSL_UsbEpHandle hEp, Uint16 byteCnt, void * data, CSL_UsbIoFlags flags)
============================================================================
USB_postTransaction
Description
This function transmits and receives USB data through an endpoint.
Arguments
            hEp         Handle to an initialized endpoint object.
            byteCnt     Total number of bytes in the buffer pointed by *data
            Data        Pointer to a data buffer
            flags       ORed combination of USB Data Transfer Flags
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB init end point should be called successfully
Post Condition
Starts the data transfer
Modifies
USB FIFO registers/data buffer
Example
             Uint16             dataBuf[256];
            CSL_UsbDevHandle   hUsbDev
             CSL_UsbEpHandle    hEp;
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ....
            status = USB_postTransaction(hEp, 256, dataBuf, CSL_USB_IOFLAG_NONE);
============================================================================
Referenced by AC_reqGetConfiguration(), AC_reqGetInterface(), AC_reqGetMaxLUN(), AC_reqGetStatus(), CDC_reqGetConfiguration(), CDC_reqGetInterface(), CDC_reqGetMaxLUN(), CDC_reqGetStatus(), HID_reqGetConfiguration(), HID_reqGetDescriptor(), HID_reqGetInterface(), HID_reqGetMaxLUN(), HID_reqGetStatus(), MSC_HandleInquiry(), MSC_HandleModeSense10(), MSC_HandleModeSense6(), MSC_HandleRequestSense(), MSC_HandleStartStopUnit(), MSC_HandleStateReset(), MSC_HandleStateSendCSW(), MSC_HandleStateSendData(), MSC_HandleStateSendingShortPkt(), MSC_HandleStateSendStall(), MSC_HandleVerify10(), MSC_reqGetConfiguration(), MSC_reqGetInterface(), MSC_reqGetMaxLUN(), and MSC_reqGetStatus().
static CSL_Status USB_processEP0In (CSL_UsbDevHandle hUsbDev) [inline, static]
============================================================================
USB_processEP0In
Description
Writes data to End point 0
Arguments
             hUsbDev      -  USB device handle
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Writes data to end point0
Modifies
Ep0 FIFO registers
Example
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
            ....
            ....
            status = USB_processEP0In(hUsbDev);
============================================================================
References CSL_UsbTransfer::cbBuffer, CSL_UsbTransfer::cbTransferred, CSL_UsbContext::completeTransferCallback, CSL_ESYS_INVPARAMS, CSL_SOK, CSL_USB_EP0, CSL_USB_EP0_IDLE, CSL_USB_MAX_EP0_FIFO_LEN, CSL_USB_MIN, CSL_UsbEpStatus::dwPacketSizeAssigned, CSL_UsbContext::ep0State, CSL_UsbTransfer::fComplete, CSL_UsbContext::fEP0BUFAvailable, CSL_UsbContext::fWaitingOnEP0BUFAvail, CSL_UsbContext::pEpStatus, CSL_UsbTransfer::prevTxferLen, CSL_UsbEpStatus::pTransfer, and CSL_UsbTransfer::pvBuffer.
static CSL_Status USB_processEP0Out (CSL_UsbDevHandle hUsbDev) [inline, static]
============================================================================
USB_processEP0Out
Description
Reads the data from End point 0
Arguments
             hUsbDev      -   USB device handle
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Reads data from end point0
Modifies
Ep0 data buffer
Example
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
            ....
            ....
            status = USB_processEP0Out(hUsbDev);
============================================================================
References CSL_UsbTransfer::cbBuffer, CSL_UsbContext::cbOutEP0Buf, CSL_UsbTransfer::cbTransferred, CSL_UsbContext::completeTransferCallback, CSL_ESYS_INVPARAMS, CSL_SOK, CSL_USB_EP0, CSL_USB_MIN, CSL_UsbContext::dwOutEP0Buf, CSL_UsbTransfer::fComplete, CSL_UsbContext::fOutPhaseCmd, CSL_UsbContext::pEpStatus, CSL_UsbTransfer::prevTxferLen, CSL_UsbEpStatus::pTransfer, and CSL_UsbTransfer::pvBuffer.
static CSL_Status USB_readEP0Buf (CSL_UsbDevHandle hUsbDev, DWORD * pBuf) [inline, static]
============================================================================
USB_readEP0Buf
Description
This function reads the End point0 buffer
Arguments
             hUsbDev       -   USB device handle
             pBusSpeed     -   USB Bus speed variable pointer
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_FAIL - Returned for failure
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Reads Ep0 data
Modifies
Ep0 Buffer
Example
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpConfig  epCfg
            CSL_UsbEpHandle  hEp
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_configEndpt(hEp, &epCfg);
            ....
            ....
            status = USB_readEP0Buf(hUsbDev, hUsbDev->dwOutEP0Buf);
============================================================================
References CSL_UsbContext::cbOutEP0DataReceived, CSL_ESYS_FAIL, CSL_SOK, CSL_USB_MAX_EP0_FIFO_LEN, and CSL_UsbContext::dwOutEP0Buf.
CSL_Status USB_releaseEndpt (CSL_UsbEpHandle hEp)
============================================================================
USB_releaseEndpt
Description
Function to release an endpoint
Arguments
            hEp          Endpoint handle
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_init, USB_open, USB_config and USB_requestEndpt functions should be called successfully
Post Condition
Releases endpoint
Modifies
USB endpoint structure
Example
            CSL_UsbDevNum    devNum;
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpHandle  hEp
            devNum = CSL_USB0;
            .....
            .....
            USB_init();
            hUsbDev = USB_open(devNum);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            status = USB_releaseEndpt(hEp);
============================================================================
CSL_UsbEpHandle USB_requestEndpt (CSL_UsbDevHandle hUsbDev, CSL_UsbEpNum epNum, CSL_Status * status)
============================================================================
USB_requestEndpt
Description
Function to request the endpoint for data communication
Arguments
            hUsbDev          USB device handle
            epNum            End point number
            *status          Return status
Return Value CSL_UsbEpHandle
Valid handle - Returned for success
NULL - Invalid parameter
Pre Condition
USB_init, USB_open and USB_config functions should be called successfully
Post Condition
Returns handle to endpoint
Modifies
USB endpoint structure
Example
            CSL_UsbDevNum    devNum;
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            CSL_UsbEpHandle  hEp
            devNum = CSL_USB0;
            .....
            .....
            USB_init();
            hUsbDev = USB_open(devNum);
            status = USB_config(hUsbDev, &usbCfg);
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
============================================================================
CSL_Status USB_resetDev (CSL_UsbDevHandle hUsbDev)
============================================================================
USB_resetDev
Description
This function resets the USB device
Arguments
            hUsbDev        USB device handle
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_init and USB_open should be called successfully
Post Condition
Resets the USB device
Modifies
USB registers
Example
            CSL_UsbDevHandle   hUsbDev;
            CSL_Status         status;
            usbConfig.maxCurrent = 50;
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            ....
            status = USB_resetDev(hUsbDev);
============================================================================
CSL_Status USB_selfwakeup (CSL_UsbDevHandle hUsbDev, Uint32 wakeupDelay)
============================================================================
USB_selfwakeup
Description
This function issues a self wakeup signal on the bus. This function can be mapped to an external event like pressing a button on the EVM. After responding to that event through a call back, USB device send a wakeup signal on the bus. NOTE: Application needs to send a delay as a parameter to this function. According to USB wakeup specification an approximate delay of 10mSecs(Min 2 to Max 15 mSecs) is required to send a wakeup signal on the bus. This delay is introduced between setting the resume bit to '1' and restting it to '0'. Application needs to decide a delay such that it is maximum enough to satisfy USB wakeup protocol and minimum to satisfy the USB driver performance.
Arguments
            hUsbDev       USB device handle
            wakeupDelay   Delay between Resume bit set and reset
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB init be called successfully and an external event should occur.
Post Condition
Send a wakeup signal on the bus.
Modifies
USB FADDR_POWER register
Example
            CSL_UsbDevHandle   hUsbDev
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ....
            ....
            //This function call should be mapped to an external event
            wakeupDelay = 1000000;
            status = USB_selfwakeup(hUsbDev, wakeupDelay);
============================================================================
static void USB_setConfiguration (CSL_UsbDevHandle hUsbDev, Uint16 confVal) [inline, static]
============================================================================
USB_setConfiguration
Description
This function sets the end point configuration This is provided to use with MSC module This function is not required for standalone MUSB testing
Arguments
             hUsbDev       -   USB device handle
             confVal       -   configuration value
Return Value None
Pre Condition
USB_initEndptObj function should be called successfully
Post Condition
Sets the end point configuration
Modifies
None
Example
            CSL_UsbDevHandle hUsbDev;
            CSL_Status       status;
            CSL_UsbConfig    usbCfg
            .....
            .....
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            status = USB_config(hUsbDev, &usbCfg);
            ....
            ....
            status = USB_setConfiguration(hUsbDev, 0x02);
============================================================================
References CSL_USB_EP1, CSL_USB_EP2, CSL_USB_EP3, CSL_USB_EP4, and CSL_UsbContext::devNum.
Referenced by AC_reqSetConfiguration(), CDC_reqSetConfiguration(), CDC_reqSetInterface(), HID_reqSetConfiguration(), MSC_reqSetConfiguration(), and MSC_reqSetInterface().
CSL_Status USB_setDevAddr (CSL_UsbDevHandle hUsbDev, Uint16 addr)
============================================================================
USB_setDevAddr
Description
This function sets the device Address to USB controller
Arguments
            hUsbDev       USB device handle
            addr          Address to set
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB_init should be called successfully
Post Condition
Configures device address registers
Modifies
Device address registers
Example
            CSL_UsbDevHandle   hUsbDev
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            ....
            status = USB_setDevAddr(hUsbDev, addr);
============================================================================
Referenced by AC_reqSetAddress(), CDC_reqSetAddress(), HID_reqSetAddress(), and MSC_reqSetAddress().
void USB_setFullSpeedMode (CSL_UsbDevHandle hUsbDev, Uint16 ep0DataSize)
============================================================================
USB_setFullSpeedMode
Description
This function is used to set the USB controller into full speed mode ep0DataSize is the size of the EP0 FIFO. This value should be within the range of values recommended by the USB specification.
Arguments
             hUsbDev       USB device handle
            ep0DataSize   Endpoint 0 data size
Return Value None
Pre Condition
USB Init should be called successfully
Post Condition
USB will be set for full speed mode
Modifies
USB registers
Example
            CSL_UsbDevHandle   hUsbDev
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            ....
            USB_setFullSpeedMode(hUsbDev, 0x20);
============================================================================
CSL_Status USB_setParams (CSL_UsbDevHandle hUsbDev, CSL_UsbEpHandle hEpObj[], Uint16 pSofTmrCnt)
============================================================================
USB_setParams
Description
This function initializes the global end point handle array
Arguments
            hUsbDev       USB device handle
            hEpObj        Pointer to a array of endpoint handle.
            pSofTmrCnt    8-bit counter value for the pre SOF timer.
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
None
Post Condition
Initializes global end point handle array
Modifies
Global end point handle array
Example
            CSL_UsbEpObj    hEpHandleArray[CSL_USB_ENDPOINT_COUNT];
            CSL_Status      status;
            status = USB_setParams(hUsbDev, &hEpHandleArray, 0);
============================================================================
CSL_Status USB_setRemoteWakeup (CSL_UsbDevHandle hUsbDev, CSL_UsbBoolean rmtWkpStat)
============================================================================
USB_setRemoteWakeup
Description
This function sets or clears Remote Wakeup Feature.
Arguments
            hUsbDev       USB device handle
            rmtWkpStat    Remote wake up status flag
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB init function should be called successfully.
Post Condition
Sets the remote wake up status
Modifies
Remote wakeup status variable in the USB global context structure
Example
            CSL_UsbDevHandle   hUsbDev
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            ....
            status = USB_setRemoteWakeup(hUsbDev, CSL_USB_TRUE);
============================================================================
Referenced by AC_reqClearFeature(), AC_reqSetFeature(), CDC_reqClearFeature(), CDC_reqSetFeature(), HID_reqClearFeature(), HID_reqSetFeature(), MSC_reqClearFeature(), and MSC_reqSetFeature().
CSL_Status USB_stallEndpt (CSL_UsbEpHandle hEp)
============================================================================
USB_stallEndpt
Description
This function stalls an end point
Arguments
            hEp         Handle to an initialized endpoint object.
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid end point handle
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
End point init function should be called successfully
Post Condition
Stalls an end point associated with the passed handle
Modifies
USB control registers
Example
             Uint16             dataBuf[256];
            CSL_UsbDevHandle   hUsbDev
             CSL_UsbEpHandle    hEp;
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ...
            status = USB_stallEndpt(hEp);
============================================================================
Referenced by AC_reqSetFeature(), CDC_reqSetFeature(), HID_reqSetFeature(), MSC_HandleModeSense10(), MSC_HandleModeSense6(), MSC_HandleStartStopUnit(), MSC_HandleStateSendingShortPkt(), MSC_HandleVerify10(), and MSC_reqSetFeature().
CSL_Status USB_suspendDevice (CSL_UsbDevHandle hUsbDev)
============================================================================
USB_suspendDevice
Description
This function suspends the USB device. This function informs the application about the device suspend through a call back function.
Arguments
            hUsbDev         USB device handle
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
USB init be called successfully.
Post Condition
Puts the USB device into suspend mode.
Modifies
USB FADDR_POWER register
Example
            CSL_UsbDevHandle   hUsbDev
            CSL_Status         status;
            USB_init();
            hUsbDev = USB_open(CSL_USB0);
            ....
            hEp = USB_requestEndpt(hUsbDev, CSL_USB_OUT_EP0, &status);
            ....
            ....
            status = USB_suspendDevice(hUsbDev);
============================================================================
static CSL_Status USB_swapWords (Uint16 * dataBuffer, Uint32 dataLength) [inline, static]
===========================================================================
USB_swapWords
Description
This function swaps words in a given buffer
Arguments
            dataBuffer    Pointer to the buffer which words needs to be swapped
            dataLength    Length of data to be word swapped (In words)
Return Value CSL_Status
CSL_SOK - Reset successful
CSL_ESYS_INVPARAMS - Invalid parameters
Pre Condition
None
Post Condition
None
Modifies
Order of data in the given buffer
Example
            #define USB_PACKET_SIZE (256)
            Uint16        usbBuf [USB_PACKET_SIZE];
            CSL_Status    status;
            status = USB_swapWords (usbBuf, USB_PACKET_SIZE);
===========================================================================
References CSL_ESYS_INVPARAMS, and CSL_SOK.
Referenced by USB_confDmaTx(), and USB_dmaRxStop().