C55XX CSL LP: USB HID Functions
USB HID Functions
HID
Functions
CSL_Status HID_Open (pHidAppClassHandle pAppClassHandle, CSL_UsbConfig *usbConfig)
CSL_Status HID_Close (pHidAppClassHandle pAppClassHandle)
CSL_Status HID_Ctrl (void *pHidObj)
CSL_Status HID_reportHandler (void *pHidObj)
CSL_Status HID_initDescriptors (void *pHidObj, Uint16 *descBuf, CSL_HidDescrId descrId, Uint16 descrLen)
static CSL_Status HID_initVal (CSL_HidObject *phidHandle)
CSL_HidRequestRet HID_reqHidGetReport (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
void HID_eventHandler (pUsbContext pContext, pHidAppClassHandle pHidAppHandle, CSL_UsbSetupStruct *usbSetUp)
static CSL_HidRequestRet HID_reqUnknown (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static fpHID_REQ_HANDLER HID_lookupReqHandler (Uint16 request, CSL_HidRequestStruct *pUSB_ReqTable)
static CSL_HidRequestRet HID_reqSetAddress (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static CSL_HidRequestRet HID_reqGetDescriptor (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static CSL_HidRequestRet HID_reqSetConfiguration (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static CSL_HidRequestRet HID_reqClearFeature (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static CSL_HidRequestRet HID_reqGetStatus (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static CSL_HidRequestRet HID_reqSetFeature (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static CSL_HidRequestRet HID_reqGetConfiguration (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static CSL_HidRequestRet HID_reqGetMaxLUN (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static CSL_HidRequestRet HID_reqSetInterface (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
static CSL_HidRequestRet HID_reqGetInterface (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct *usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void *pHidObj)
Function Documentation
CSL_Status HID_Close (pHidAppClassHandle pAppClassHandle)
============================================================================
HID_Close
Description
This function Closes the Hid class module.
Arguments
            pAppClassHandle       Application handle to the Hid Class Obj
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid Hid class handle
Pre Condition
HID_Open function should be called successfully
Post Condition
Closes the Hid Class module
Modifies
Hid and Ctl handles
Example
            CSL_HidInitStructApp    hidAppHandle;
            pHidAppClassHandle      pAppClassHandle;
            Uint16                 hidAppBuffer[420];
            CSL_Status             status;
            pAppClassHandle = &hidAppHandle;
            // Assign values to all the members in hidAppHandle struct
            hidAppHandle.pHidObj = &hidAppBuffer[0];
            .....
            .....
            status = HID_Open(pAppClassHandle);
            ....
            ....
            status = HID_Close(pAppClassHandle);
============================================================================
CSL_Status HID_Ctrl (void * pHidObj)
============================================================================
HID_Ctrl
Description
This function handles all USB traffic on the Control Endpoint. Detects the events on the Control Endpoint and takes the appropriate action
Arguments
            pHidObj        Handle to the Hid Class Obj
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid Hid class handle
CSL_HID_INVALID_REQUEST_HANDLER - Invalid request class handler
Pre Condition
HID_Open function should be called successfully
Post Condition
Control end point events are serviced
Modifies
USB Registers.
Example
            CSL_HidInitStructApp    hidAppHandle;
            pHidAppClassHandle      pAppClassHandle;
            Uint16                 hidAppBuffer[420];
            CSL_Status             status;
            pAppClassHandle = &hidAppHandle;
            // Assign values to all the members in hidAppHandle struct
            hidAppHandle.pHidObj = &hidAppBuffer[0];
            .....
            .....
            status = HID_Open(pAppClassHandle);
            ....
            ....
            status = HID_Ctrl(pAppClassHandle->pHidObj);
============================================================================
void HID_eventHandler (pUsbContext pContext, pHidAppClassHandle pHidAppHandle, CSL_UsbSetupStruct * usbSetUp)
============================================================================
HID_eventHandler
Description
This function handles all HID data transactions
Arguments
            pContext         Pointer to the USBContext structure
            hHidClass        Handle to the HID Class Obj
            usbSetUp         Structure to hold the USB Set up Values that were
                             used to configure the USB End Point
Return Value - Status of the processing (CSL_Status)
CSL_SOK (0) Success
CSL_ESYS_FAIL (-1) Generic failure
CSL_ESYS_BADHANDLE (-5) Handle passed to CSL was invalid
CSL_ESYS_INVPARAMS (-6) Invalid parameters
Pre Condition
HID module should be opened using HID_Open function
Post Condition
Returns request processing status
Modifies
None
Example
            CSL_HidInitStructApp    pHidAppHandle;
            CSL_HidClassStruct      hidClassStruct;
            CSL_UsbSetupStruct      usbSetUp;
            CSL_Status              status;
            // Assign values to all the members in hidAppHandle struct
            hidAppHandle.pHidObj = &hidClassStruct;
            .....
            .....
            status = HID_Open(pHidAppHandle);
            ....
            ....
            in USB ISR:
            ....
            ....
            if (pContext->dwIntSourceL & (1<<CSL_USB_IN_EP0))
            {
                // Handle the HID Event
                HID_eventHandler(pContext, &pHidAppHandle, &usbSetUp);
            }
            ....
            ....
============================================================================
CSL_Status HID_initDescriptors (void * pHidObj, Uint16 * descBuf, CSL_HidDescrId descrId, Uint16 descrLen)
============================================================================
HID_initDescriptors
Description
This function initializes the descriptors used by the USB Hid class
Arguments
            pHidObj      Hid Class object
            descBuf     Descriptor buffer pointer
            descrId     Id of the Descriptor to initialize
            descrLen    Length of the descriptor to initialize (in bytes)
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid Ctrl handle
CSL_ESYS_INVPARAMS - Invalid parameter
Pre Condition
None
Post Condition
Initializes descriptors
Modifies
Descriptor buffers
Example
            CSL_HidInitStructApp    hidAppHandle;
            pHidAppClassHandle      pAppClassHandle;
            Uint16                 hidAppBuffer[420];
            CSL_Status             status;
            pAppClassHandle = &hidAppHandle;
            // Assign values to all the members in hidAppHandle struct
            hidAppHandle.pHidObj = &hidAppBuffer[0];
            status = HID_initDescriptors(pAppClassHandle->pHidObj,
                                        CSL_HID_DEVICE_DESCR, 18);
============================================================================
static CSL_Status HID_initVal (CSL_HidObject * phidHandle) [static]
============================================================================
HID_initHidVal
Description
This function initializes the Hid Class object
Arguments
            phidHandle        Handle to the Hid class Object
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid Hid class handle
Pre Condition
None
Post Condition
Initializes Hid Class object
Modifies
Hid Class object structure
Example
            CSL_HidObject    hidObj;
            CSL_Status      status;
            status = HID_initHidVal(&hidObj);
============================================================================
static fpHID_REQ_HANDLER HID_lookupReqHandler (Uint16 request, CSL_HidRequestStruct * pUSB_ReqTable) [inline, static]
============================================================================
HID_lookupReqHandler
Description
This functions maps the request sent by host to the Hid request table and returns the correspending request handler address
Arguments
            request        -  Request sent by the host
            pUSB_ReqTable  -  Request table structure pointer
Return Value
Request handler pointer
Pre Condition
Request table should be initialized and HID_Open function should be called successfully
Post Condition
Returns the request handler pointer
Modifies
None
Example
             CSL_HidRequestRet      (*fpRequestHandler)(CSL_HID_REQUEST_ARGS)
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
============================================================================
References CSL_HidRequestStruct::fpRequestHandler, and HID_reqUnknown().
CSL_Status HID_Open (pHidAppClassHandle pAppClassHandle, CSL_UsbConfig * usbConfig)
============================================================================
HID_Open
Description
This function Opens the Hid class module. It initializes Hid and Ctrl handles with the data given by the application
Arguments
            pAppClassHandle      Application handle to the Hid Class Obj
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid Hid class handle
Pre Condition
None
Post Condition
Initializes Hid and Ctrl handles
Modifies
Hid and Ctrl handle data
Example
            CSL_HidInitStructApp    hidAppHandle;
            pHidAppClassHandle      pAppClassHandle;
            Uint16                 hidAppBuffer[420];
            CSL_Status             status;
            pAppClassHandle = &hidAppHandle;
            // Assign values to all the members in hidAppHandle struct
            hidAppHandle.pHidObj = &hidAppBuffer[0];
            .....
            .....
            status = HID_Open(pAppClassHandle);
============================================================================
CSL_Status HID_reportHandler (void * pHidObj)
============================================================================
HID_reportHandler
Description
This function handles all USB traffic on the HID Interrupt Endpoint. Detects the events on the HID Endpoint and takes the appropriate action
Arguments
            pHidObj        Handle to the Hid Class Obj
Return Value CSL_Status
CSL_SOK - Returned for success
CSL_ESYS_BADHANDLE - Invalid Hid class handle
CSL_HID_INVALID_REQUEST_HANDLER - Invalid request class handler
Pre Condition
HID_Open function should be called successfully
Post Condition
HID interrupt end point events are serviced
Modifies
USB Registers.
Example
            CSL_HidInitStructApp    hidAppHandle;
            pHidAppClassHandle      pAppClassHandle;
            Uint16                 hidAppBuffer[420];
            CSL_Status             status;
            pAppClassHandle = &hidAppHandle;
            // Assign values to all the members in hidAppHandle struct
            hidAppHandle.pHidObj = &hidAppBuffer[0];
            .....
            .....
            status = HID_Open(pAppClassHandle);
            ....
            ....
            status = HID_reportHandler(pAppClassHandle->pHidObj);
============================================================================
static CSL_HidRequestRet HID_reqClearFeature (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqClearFeature
Description
This function handles the request to clear the feature set
Arguments
            devNum       - USB device number
            usbSetup     - USb setup structure
            hInEp        - USB ISO In end point handle
            hOutEp       - USB ISO Out end point object
            pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_SEND_ACK - Send acknowledgement for request
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Clears the feature
Modifies
USB registers
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
References CSL_USB_FEATURE_ENDPOINT_STALL, CSL_USB_FEATURE_REMOTE_WAKEUP, CSL_UsbContext::hEpHandleArray, USB_clearEndptStall(), USB_setRemoteWakeup(), and CSL_UsbSetupStruct::wValue.
static CSL_HidRequestRet HID_reqGetConfiguration (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqGetConfiguration
Description
This function handles the request from host to get configuration
Arguments
            devNum       - USB device number
            usbSetup     - USb setup structure
            hInEp        - USB ISO In end point handle
            hOutEp       - USB ISO Out end point object
            pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_GET_ACK - Get acknowledgement for request
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sends the configuration
Modifies
None
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
References CSL_USB_IN_TRANSFER, CSL_HidCtrlObject::ctrlBuffer, CSL_HidClassStruct::ctrlHandle, CSL_HidCtrlObject::curConfigStat, and USB_postTransaction().
static CSL_HidRequestRet HID_reqGetDescriptor (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqGetDescriptor
Description
This function handles the request from host to get the descriptor
Arguments
            CSL_HID_REQUEST_ARGS    - HID request arguments
Return Value
CSL_HID_REQUEST_GET_ACK - Get acknowledgement for request\
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sends the descriptor
Modifies
None
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHID);
============================================================================
References CSL_HidCtrlObject::confDescr, CSL_HID_8BIT_SHIFT, CSL_USB_CONFIGURATION_DESCRIPTOR_TYPE, CSL_USB_DEVICE_DESCRIPTOR_TYPE, CSL_USB_DEVICE_QUAL_DESCRIPTOR_TYPE, CSL_USB_ENDPOINT_DESCRIPTOR_TYPE, CSL_USB_HID_DESCRIPTOR_TYPE, CSL_USB_HID_REPORT_DESCRIPTOR_TYPE, CSL_USB_IN_TRANSFER, CSL_USB_INTERFACE_DESCRIPTOR_TYPE, CSL_USB_IOFLAG_CAT, CSL_USB_IOFLAG_LNK, CSL_USB_IOFLAG_NONE, CSL_USB_IOFLAG_NOSHORT, CSL_USB_OTHERSPEED_CFG_DESCRIPTOR_TYPE, CSL_USB_STRING_DESCRIPTOR_TYPE, CSL_HidClassStruct::ctrlHandle, CSL_HidCtrlObject::deviceDescr, CSL_HidCtrlObject::deviceQualifierDescr, CSL_HidCtrlObject::hidClassHidReportDescr, CSL_HidCtrlObject::hidClassHidReportDescrLen, CSL_HidCtrlObject::osConfDescr, CSL_HidCtrlObject::strDescr, USB_postTransaction(), CSL_UsbSetupStruct::wLength, and CSL_UsbSetupStruct::wValue.
static CSL_HidRequestRet HID_reqGetInterface (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqGetInterface
Description
This function handles the request from host to get interafce unit number
Arguments
             devNum       - USB device number
             usbSetup     - USb setup structure
             hInEp        - USB ISO In end point handle
             hOutEp       - USB ISO Out end point object
             pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_GET_ACK - Get acknowledgement for request\
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sends interface info
Modifies
None
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
References CSL_USB_IOFLAG_NONE, CSL_HidCtrlObject::ctrlBuffer, CSL_HidClassStruct::ctrlHandle, USB_postTransaction(), CSL_UsbSetupStruct::wIndex, CSL_UsbSetupStruct::wLength, and CSL_UsbSetupStruct::wValue.
static CSL_HidRequestRet HID_reqGetMaxLUN (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqGetMaxLUN
Description
This function handles the request from host to send maximum logical unit number
Arguments
             devNum       - USB device number
             usbSetup     - USb setup structure
             hInEp        - USB ISO In end point handle
             hOutEp       - USB ISO Out end point object
             pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_GET_ACK - Get acknowledgement for request\
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sends the max lun number
Modifies
None
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
References CSL_USB_IOFLAG_NONE, CSL_HidCtrlObject::ctrlBuffer, CSL_HidClassStruct::ctrlHandle, CSL_HidClassStruct::hidHandle, CSL_HidObject::noOfLun, and USB_postTransaction().
static CSL_HidRequestRet HID_reqGetStatus (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqGetStatus
Description
This function handles the get status request from host
Arguments
            devNum       - USB device number
            usbSetup     - USb setup structure
            hInEp        - USB ISO In end point handle
            hOutEp       - USB ISO Out end point object
            pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_GET_ACK - Get acknowledgement for request
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sends the status
Modifies
None
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
References CSL_UsbSetupStruct::bmRequestType, CSL_HID_REQUEST_TYPE_BASE, CSL_HID_REQUEST_TYPE_DEVICE_STATUS, CSL_HID_REQUEST_TYPE_EP_STATUS, CSL_HID_REQUEST_TYPE_INTERFACE_STATUS, CSL_USB_IOFLAG_NONE, CSL_HidCtrlObject::ctrlBuffer, CSL_HidClassStruct::ctrlHandle, CSL_UsbContext::hEpHandleArray, USB_getEndptStall(), USB_getRemoteWakeupStat(), and USB_postTransaction().
CSL_HidRequestRet HID_reqHidGetReport (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj)
============================================================================
HID_reqHidGetReport
Description
This function handles the request from host to get HID report
Arguments
             devNum       - USB device number
             usbSetup     - USb setup structure
             hInEp        - USB ISO In end point handle
             hOutEp       - USB ISO Out end point object
             pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_SEND_ACK - Send acknowledgement for request
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sends acknowledgement
Modifies
None
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
static CSL_HidRequestRet HID_reqSetAddress (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqSetAddress
Description
This function handles the request to set the device address
Arguments
            devNum       - USB device number
            usbSetup     - USb setup structure
            hInEp        - USB ISO In end point handle
            hOutEp       - USB ISO Out end point object
            pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_DONE - Request hadled successfully
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sets the device address
Modifies
USB FADDR_POWER register
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
References USB_setDevAddr(), usbRegisters, and CSL_UsbSetupStruct::wValue.
static CSL_HidRequestRet HID_reqSetConfiguration (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqSetConfiguration
Description
This function handles the request to set the device configuration
Arguments
            devNum       - USB device number
            usbSetup     - USb setup structure
            hInEp        - USB ISO In end point handle
            hOutEp       - USB ISO Out end point object
            pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_SEND_ACK - Send acknowledgement for request
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sets the configuration
Modifies
USB registers
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
References CSL_HidClassStruct::ctrlHandle, CSL_HidCtrlObject::curConfigStat, USB_setConfiguration(), and CSL_UsbSetupStruct::wValue.
static CSL_HidRequestRet HID_reqSetFeature (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqSetFeature
Description
This function handles the request from host to set feature
Arguments
            devNum       - USB device number
            usbSetup     - USb setup structure
            hInEp        - USB ISO In end point handle
            hOutEp       - USB ISO Out end point object
            pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_GET_ACK - Get acknowledgement for request
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sets the feature
Modifies
USB regiters
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
References CSL_USB_FEATURE_ENDPOINT_STALL, CSL_USB_FEATURE_REMOTE_WAKEUP, CSL_UsbContext::hEpHandleArray, USB_setRemoteWakeup(), USB_stallEndpt(), and CSL_UsbSetupStruct::wValue.
static CSL_HidRequestRet HID_reqSetInterface (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqSetInterface
Description
This function handles the request from host to set interafce unit number
Arguments
             devNum       - USB device number
             usbSetup     - USb setup structure
             hInEp        - USB ISO In end point handle
             hOutEp       - USB ISO Out end point object
             pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_SEND_ACK - Send acknowledgement for request
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sends acknowledgement
Modifies
None
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
References usbRegisters, CSL_UsbSetupStruct::wIndex, CSL_UsbSetupStruct::wLength, and CSL_UsbSetupStruct::wValue.
static CSL_HidRequestRet HID_reqUnknown (CSL_UsbDevHandle devHandle, CSL_UsbSetupStruct * usbSetup, CSL_UsbEpHandle hInEp, CSL_UsbEpHandle hOutEp, void * pHidObj) [inline, static]
============================================================================
HID_reqUnknown
Description
This function handles the case where the request sent by the host is unknown unit number
Arguments
            devNum       - USB device number
            usbSetup     - USb setup structure
            hInEp        - USB ISO In end point handle
            hOutEp       - USB ISO Out end point object
            pHidObj       - USB Hid Class object
Return Value
CSL_HID_REQUEST_STALL - Request stall signal (Error)
Pre Condition
HID_lookupReqHandler should be called successfully
Post Condition
Sends acknowledgement
Modifies
None
Example
             CSL_HidInitStructApp   hidAppHandle;
             CSL_HidObject          *phidHandle;
             CSL_HidCtrlObject      *pCtrlHandle;
             CSL_UsbEpHandle        hUbOutEp;
             Uint16                 lunNum;
             Uint16                 hidAppBuffer[420];
             CSL_Status             status;
             Uint16                 request;
             // Assign values to all the members in hidAppHandle struct
             hidAppHandle.pHidObj = &hidAppBuffer[0];
             .....
             .....
             status = HID_Open(&hidAppHandle);
             ....
             ....
             pCtrlHandle->fpRequestHandler = HID_lookupReqHandler(request,
                                                       pCtrlHandle->hidReqTable);
             pCtrlHandle->fpRequestHandler(pCtrlHandle->devNum,
                                           &pCtrlHandle->usbSetup,hCtrlEpIn,hCtrlEpOut,pHidObj);
============================================================================
Referenced by HID_lookupReqHandler().